# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_pb2 as message__pb2
import user_pb2 as user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat_server.proto',
  package='chating.server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63hat_server.proto\x12\x0e\x63hating.server\x1a\rmessage.proto\x1a\nuser.proto\")\n\x05Hello\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.chating.user.User\">\n\x04Ping\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.chating.user.User\x12\x14\n\x0cmessageCount\x18\x02 \x01(\x05\"L\n\x04Pong\x12\x1e\n\x02ok\x18\x01 \x01(\x0b\x32\x12.chating.server.Ok\x12$\n\x05state\x18\x02 \x01(\x0e\x32\x15.chating.server.State\"2\n\x02Ok\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x14\n\x0cmessageCount\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05*\x1b\n\x05State\x12\x08\n\x04IDLE\x10\x00\x12\x08\n\x04\x42USY\x10\x01\x32\xf8\x01\n\nChatServer\x12\x32\n\x05Login\x12\x15.chating.server.Hello\x1a\x12.chating.server.Ok\x12\x39\n\x0bPingRequest\x12\x14.chating.server.Ping\x1a\x14.chating.server.Pong\x12\x39\n\nGetMessage\x12\x12.chating.server.Ok\x1a\x15.chating.message.Chat0\x01\x12@\n\x0bSendMessage\x12\x1d.chating.message.ChatMessages\x1a\x12.chating.server.Okb\x06proto3'
  ,
  dependencies=[message__pb2.DESCRIPTOR,user__pb2.DESCRIPTOR,])

_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='chating.server.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=301,
  serialized_end=328,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
IDLE = 0
BUSY = 1



_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='chating.server.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='chating.server.Hello.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=105,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='chating.server.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='chating.server.Ping.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageCount', full_name='chating.server.Ping.messageCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=169,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='chating.server.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='chating.server.Pong.ok', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='chating.server.Pong.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=247,
)


_OK = _descriptor.Descriptor(
  name='Ok',
  full_name='chating.server.Ok',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='chating.server.Ok.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageCount', full_name='chating.server.Ok.messageCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='chating.server.Ok.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=299,
)

_HELLO.fields_by_name['user'].message_type = user__pb2._USER
_PING.fields_by_name['user'].message_type = user__pb2._USER
_PONG.fields_by_name['ok'].message_type = _OK
_PONG.fields_by_name['state'].enum_type = _STATE
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['Ok'] = _OK
DESCRIPTOR.enum_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), {
  'DESCRIPTOR' : _HELLO,
  '__module__' : 'chat_server_pb2'
  # @@protoc_insertion_point(class_scope:chating.server.Hello)
  })
_sym_db.RegisterMessage(Hello)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'chat_server_pb2'
  # @@protoc_insertion_point(class_scope:chating.server.Ping)
  })
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'chat_server_pb2'
  # @@protoc_insertion_point(class_scope:chating.server.Pong)
  })
_sym_db.RegisterMessage(Pong)

Ok = _reflection.GeneratedProtocolMessageType('Ok', (_message.Message,), {
  'DESCRIPTOR' : _OK,
  '__module__' : 'chat_server_pb2'
  # @@protoc_insertion_point(class_scope:chating.server.Ok)
  })
_sym_db.RegisterMessage(Ok)



_CHATSERVER = _descriptor.ServiceDescriptor(
  name='ChatServer',
  full_name='chating.server.ChatServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=331,
  serialized_end=579,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='chating.server.ChatServer.Login',
    index=0,
    containing_service=None,
    input_type=_HELLO,
    output_type=_OK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PingRequest',
    full_name='chating.server.ChatServer.PingRequest',
    index=1,
    containing_service=None,
    input_type=_PING,
    output_type=_PONG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMessage',
    full_name='chating.server.ChatServer.GetMessage',
    index=2,
    containing_service=None,
    input_type=_OK,
    output_type=message__pb2._CHAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='chating.server.ChatServer.SendMessage',
    index=3,
    containing_service=None,
    input_type=message__pb2._CHATMESSAGES,
    output_type=_OK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVER)

DESCRIPTOR.services_by_name['ChatServer'] = _CHATSERVER

# @@protoc_insertion_point(module_scope)
