# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_pb2 as user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='chating.message',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x0f\x63hating.message\x1a\nuser.proto\";\n\x0c\x43hatMessages\x12+\n\x0c\x63hatMessages\x18\x01 \x03(\x0b\x32\x15.chating.message.Chat\"O\n\x04\x43hat\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.chating.user.User\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cmessageCount\x18\x03 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[user__pb2.DESCRIPTOR,])




_CHATMESSAGES = _descriptor.Descriptor(
  name='ChatMessages',
  full_name='chating.message.ChatMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chatMessages', full_name='chating.message.ChatMessages.chatMessages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=105,
)


_CHAT = _descriptor.Descriptor(
  name='Chat',
  full_name='chating.message.Chat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='chating.message.Chat.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='chating.message.Chat.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageCount', full_name='chating.message.Chat.messageCount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=186,
)

_CHATMESSAGES.fields_by_name['chatMessages'].message_type = _CHAT
_CHAT.fields_by_name['user'].message_type = user__pb2._USER
DESCRIPTOR.message_types_by_name['ChatMessages'] = _CHATMESSAGES
DESCRIPTOR.message_types_by_name['Chat'] = _CHAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatMessages = _reflection.GeneratedProtocolMessageType('ChatMessages', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGES,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:chating.message.ChatMessages)
  })
_sym_db.RegisterMessage(ChatMessages)

Chat = _reflection.GeneratedProtocolMessageType('Chat', (_message.Message,), {
  'DESCRIPTOR' : _CHAT,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:chating.message.Chat)
  })
_sym_db.RegisterMessage(Chat)


# @@protoc_insertion_point(module_scope)
