# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interceptSample.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import utils_pb2 as utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='interceptSample.proto',
  package='interceptors',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15interceptSample.proto\x12\x0cinterceptors\x1a\x0butils.proto\"O\n\x04Load\x12\r\n\x05value\x18\x01 \x01(\t\x12-\n\x06\x65ncode\x18\x02 \x01(\x0e\x32\x18.interceptors.encodeTypeH\x00\x88\x01\x01\x42\t\n\x07_encode\"\x14\n\x03Num\x12\r\n\x05value\x18\x01 \x01(\x05*\"\n\nencodeType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06\x42\x41SE64\x10\x01\x32\xc4\x01\n\rSecureMessage\x12\x41\n\x0bPingRequest\x12\x18.interceptors.utils.Ping\x1a\x18.interceptors.utils.Pong\x12\x35\n\x0bsendMessage\x12\x12.interceptors.Load\x1a\x12.interceptors.Load\x12\x39\n\x0f\x61\x64\x64TheseNumbers\x12\x11.interceptors.Num\x1a\x11.interceptors.Num(\x01\x62\x06proto3'
  ,
  dependencies=[utils__pb2.DESCRIPTOR,])

_ENCODETYPE = _descriptor.EnumDescriptor(
  name='encodeType',
  full_name='interceptors.encodeType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BASE64', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=155,
  serialized_end=189,
)
_sym_db.RegisterEnumDescriptor(_ENCODETYPE)

encodeType = enum_type_wrapper.EnumTypeWrapper(_ENCODETYPE)
NONE = 0
BASE64 = 1



_LOAD = _descriptor.Descriptor(
  name='Load',
  full_name='interceptors.Load',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='interceptors.Load.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encode', full_name='interceptors.Load.encode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_encode', full_name='interceptors.Load._encode',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=52,
  serialized_end=131,
)


_NUM = _descriptor.Descriptor(
  name='Num',
  full_name='interceptors.Num',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='interceptors.Num.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=153,
)

_LOAD.fields_by_name['encode'].enum_type = _ENCODETYPE
_LOAD.oneofs_by_name['_encode'].fields.append(
  _LOAD.fields_by_name['encode'])
_LOAD.fields_by_name['encode'].containing_oneof = _LOAD.oneofs_by_name['_encode']
DESCRIPTOR.message_types_by_name['Load'] = _LOAD
DESCRIPTOR.message_types_by_name['Num'] = _NUM
DESCRIPTOR.enum_types_by_name['encodeType'] = _ENCODETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Load = _reflection.GeneratedProtocolMessageType('Load', (_message.Message,), {
  'DESCRIPTOR' : _LOAD,
  '__module__' : 'interceptSample_pb2'
  # @@protoc_insertion_point(class_scope:interceptors.Load)
  })
_sym_db.RegisterMessage(Load)

Num = _reflection.GeneratedProtocolMessageType('Num', (_message.Message,), {
  'DESCRIPTOR' : _NUM,
  '__module__' : 'interceptSample_pb2'
  # @@protoc_insertion_point(class_scope:interceptors.Num)
  })
_sym_db.RegisterMessage(Num)



_SECUREMESSAGE = _descriptor.ServiceDescriptor(
  name='SecureMessage',
  full_name='interceptors.SecureMessage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=192,
  serialized_end=388,
  methods=[
  _descriptor.MethodDescriptor(
    name='PingRequest',
    full_name='interceptors.SecureMessage.PingRequest',
    index=0,
    containing_service=None,
    input_type=utils__pb2._PING,
    output_type=utils__pb2._PONG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='interceptors.SecureMessage.sendMessage',
    index=1,
    containing_service=None,
    input_type=_LOAD,
    output_type=_LOAD,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='addTheseNumbers',
    full_name='interceptors.SecureMessage.addTheseNumbers',
    index=2,
    containing_service=None,
    input_type=_NUM,
    output_type=_NUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECUREMESSAGE)

DESCRIPTOR.services_by_name['SecureMessage'] = _SECUREMESSAGE

# @@protoc_insertion_point(module_scope)
